server:
  port: 9000  # 9000번 포트로 실행

spring:
  application:
    name: demo

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
      check-template-location: true
      prefix: classpath:/templates/
      suffix: .html

  datasource:
    platform: mysql
    url: jdbc:mysql://database-2.cn6qj3gf4bmy.ap-northeast-2.rds.amazonaws.com/dok_spring1
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: admin # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: qwerrewq # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver
